# Generated by Django 5.0.2 on 2024-03-03 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostBlogContentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="タイトル",
                        help_text="最大20文字",
                        max_length=20,
                        verbose_name="タイトル",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        default="その他",
                        help_text="最大20文字",
                        max_length=20,
                        verbose_name="タグ",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(help_text="html形式で記載", verbose_name="本文"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
