# Generated by Django 4.2.14 on 2024-07-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontents',
            old_name='post_user_id',
            new_name='user',
        ),
    ]
