# Generated by Django 5.1 on 2024-09-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontents',
            name='meta_description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogcontents',
            name='meta_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
